name: nbaBuzz
description: NBA app to keep track of stats

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  provider: ^6.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  intl: ^0.18.0
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/bball.png
    - assets/images/lightning.jpg

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/bball.png
  android: true
  ios: true

